AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy lambda functions
Parameters:
  RoleArn:
    Type: String
  SecurityGroupIds:
    Type: CommaDelimitedList
  SubnetIds:
    Type: CommaDelimitedList
  NeptuneEndpoint:
    Type: String
  NeptunePort:
    Type: String
  TagUser:
    Type: String
Resources:
  CreateEmployeeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: de.consol.labs.aws.neptunedemoapp.createemployee.CreateEmployeeHandler::handleRequest
      Role:
        Ref: RoleArn
      CodeUri: s3://aryndin-neptune-demo/04db6bcd25c56eedfa2888d97ee4a174
      Environment:
        Variables:
          NEPTUNE_ENDPOINT:
            Ref: NeptuneEndpoint
          NEPTUNE_PORT:
            Ref: NeptunePort
      Timeout: 180
      MemorySize: 1024
      VpcConfig:
        SecurityGroupIds:
          Ref: SecurityGroupIds
        SubnetIds:
          Ref: SubnetIds
    Tags:
    - Key: user
      Value:
        Ref: TagUser
  ReadEmployeeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: de.consol.labs.aws.neptunedemoapp.reademployee.ReadEmployeeHandler::handleRequest
      Role:
        Ref: RoleArn
      CodeUri: s3://aryndin-neptune-demo/6808fa9a4ad2ff7f323122470fc0c6bd
      Environment:
        Variables:
          NEPTUNE_ENDPOINT:
            Ref: NeptuneEndpoint
          NEPTUNE_PORT:
            Ref: NeptunePort
      Timeout: 180
      MemorySize: 1024
      VpcConfig:
        SecurityGroupIds:
          Ref: SecurityGroupIds
        SubnetIds:
          Ref: SubnetIds
    Tags:
    - Key: user
      Value:
        Ref: TagUser
  RunAdHocQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: de.consol.labs.aws.neptunedemoapp.runadhocquery.RunAdHocQueryHandler::handleRequest
      Role:
        Ref: RoleArn
      CodeUri: s3://aryndin-neptune-demo/b8df690a01d96c5def058d5186d24e0d
      Environment:
        Variables:
          NEPTUNE_ENDPOINT:
            Ref: NeptuneEndpoint
          NEPTUNE_PORT:
            Ref: NeptunePort
      Timeout: 180
      MemorySize: 1024
      VpcConfig:
        SecurityGroupIds:
          Ref: SecurityGroupIds
        SubnetIds:
          Ref: SubnetIds
    Tags:
    - Key: user
      Value:
        Ref: TagUser
  LoadTestDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: de.consol.labs.aws.neptunedemoapp.loadtestdata.LoadTestDataHandler::handleRequest
      Role:
        Ref: RoleArn
      CodeUri: s3://aryndin-neptune-demo/edf7a47be14fc43fee1a4f34c06aa993
      Environment:
        Variables:
          NEPTUNE_ENDPOINT:
            Ref: NeptuneEndpoint
          NEPTUNE_PORT:
            Ref: NeptunePort
      Timeout: 180
      MemorySize: 1024
      VpcConfig:
        SecurityGroupIds:
          Ref: SecurityGroupIds
        SubnetIds:
          Ref: SubnetIds
    Tags:
    - Key: user
      Value:
        Ref: TagUser
